### ISSUE TITLE
A way of contact

### ISSUE THREAD

**Issue by s0uBoss** [pnwparksfan/utility-truck-interaction#1]
Sorry for creating this as issue but I could not find any other way to get in touch with you. Can you tell me what contact methods do you have ?

**Comment by pnwparksfan** [comment]
I have a [Discord server available for donors](https://parksmods.com/donate/) or you can [PM me on lcpdfr.com](https://www.lcpdfr.com/profile/258928-pnwparksfan/).

**Comment by s0uBoss** [comment]
Okay. Is there an option to contact you on discord in private? I am wondering how  can I adjust this script for FiveM

**Comment by Michael21107** [comment]
> Okay. Is there an option to contact you on discord in private? I am wondering how can I adjust this script for FiveM

@pnwparksfan
